mode = "dark"
accent = "#66e5ff"
selection = "#244967"
muted = "#527089"
background = "#081525"
dark_background = "#050e1b"
darker_background = "#030913"
lighter_background = "#142a40"
foreground = "#c5e6ff"
dark_foreground = "#7896af"
light_foreground = "#a4cce8"
bright_foreground = "#ecf8ff"
red = "#ff849e"
yellow = "#f1d59a"
orange = "#f8ad85"
green = "#80dcc1"
cyan = "#66e5ff"
blue = "#7fbaff"
magenta = "#b89aff"
brown = "#987c84"
bright_red = "#ffa0b5"
bright_yellow = "#ffe7b5"
bright_green = "#a1f0d7"
bright_cyan = "#a4f3ff"
bright_blue = "#a3d3ff"
bright_magenta = "#d6bdff"
hyprland_active_border = "rgba(66e5ffff) rgba(7fbaffff) rgba(b89affff) 45deg"
hyprland_inactive_border = "rgba(345574aa)"
